src/Application/Purchase/Entity/Cart.php
<?php

namespace App\Application\Purchase\Entity;

use App\Application\Product\Product;
use App\Application\Product\Entity\Color;

class Cart
{
    /**
     * @var CartItem[]
     */
    private array $items = [];

    public function addItem(CartItem $cartItem): CartItem
    {
        foreach ($this->items as $item) {
            if ($cartItem->matches($item)) {
                $item->increaseQuantity($cartItem->getQuantity());

                return $item;
            }
        }

        $this->items[] = $cartItem;

        return $cartItem;
    }

    public function removeItem(CartItem $cartItem)
    {
        foreach ($this->items as $key => $item) {
            if ($cartItem->matches($item)) {
                unset($this->items[$key]);
                $this->items = array_values($this->items);

                return;
            }
        }
    }

	public function isEmpty(): bool
	{
		return empty($this->items);
	}

    public function getTotalString(): string
    {
        return (string) ($this->getTotal() / 100);
    }

    public function getTotal(): int
    {
        return array_reduce($this->getItems(), function($accumulator, CartItem $item) {
            return $accumulator + $item->getTotal();
        }, 0);
    }

    /**
     * @return CartItem[]|array
     */
    public function getItems(): array
    {
        return $this->items;
    }

    public function countTotalItems(): int
    {
        return array_reduce($this->getItems(), function($accumulator, CartItem $item) {
            return $accumulator + $item->getQuantity();
        }, 0);
    }

    public function hasItem(CartItem $cartItem): bool
    {
        return (bool) $this->findItem($cartItem->getProduct(), $cartItem->getColor());
    }

    public function findItem(Product $product, ?Color $color): ?CartItem
    {
        foreach ($this->items as $item) {
            if ($item->getProduct() === $product && $item->getColor() === $color) {
                return $item;
            }
        }

        return null;
    }
}

src/Entity/Color.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ColorRepository;

#[ORM\Entity(repositoryClass: ColorRepository::class)]
class Color
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 6)]
    private ?string $hexColor = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHexColor(): ?string
    {
        return $this->hexColor;
    }

    public function setHexColor(string $hexColor): self
    {
        $this->hexColor = $hexColor;

        return $this;
    }
	public function getRed(): string
	{
		return hexdec(substr($this->hexColor, 0, 2));
	}

	public function getGreen(): string
	{
		return hexdec(substr($this->hexColor, 2, 2));
	}

	public function getBlue(): string
	{
		return hexdec(substr($this->hexColor, 4, 2));
	}
}

src/Application/Shop/Form/SearchForm.php
<?php

namespace App\Application\Shop\Form;

use Symfony\Component\Form\AbstractType;
use App\Application\Shop\Data\SearchData;
use App\Application\Product\Entity\Category;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use function Symfony\Component\Translation\t;

class SearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('q', TextType::class, [
				'label' => 'product.search',
	            'attr' => [
					'placeholder' => t("product.search")
	            ],
	            'required' => false,
            ])
            ->add('categories', EntityType::class, [
				'label' => false,
	            'required' => false,
                'class' => Category::class,
	            'expanded' => true,
	            'multiple' => true
            ])
            ->add('min', NumberType::class, [
				'label' => false,
	            'required' => false,
	            'attr' => [
					'placeholder' => t('minPrice')
	            ]
            ])
            ->add('max', NumberType::class, [
				'label' => false,
	            'required' => false,
	            'attr' => [
					'placeholder' => t('maxPrice')
	            ]
            ])
            ->add('promo', CheckboxType::class, [
				'label' => 'isPromo',
	            'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SearchData::class,
	        'method' => 'GET',
	        'csrf_protection' => false
        ]);
    }

	public function getBlockPrefix(): string
	{
		return '';
	}
}

src/Client/Controller/Shop/CartController.php
<?php

namespace App\Client\Controller\Shop;


use App\Application\Product\Product;
use App\Application\Product\Entity\Color;
use App\Infrastructure\Service\CartStorage;
use Symfony\Component\HttpFoundation\Request;
use App\Application\Product\ProductRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Application\Product\Repository\ColorRepository;
use App\Application\Purchase\Form\AddItemToCartFormType;
use App\Application\Product\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use function Symfony\Component\Translation\t;

class CartController extends AbstractController
{

	#[Route(path: '/panier', name: 'app_cart')]
    public function shoppingCart(Request $request, CartStorage $cartStorage, ProductRepository  $productRepository): Response
    {
		$cart = $cartStorage->getOrCreateCart();

        /*$featuredProduct = $productRepository->findFeatured();
        $addToCartForm = $this->createForm(AddItemToCartFormType::class, null, [
            'product' => $featuredProduct,
        ]);*/

        return $this->renderForm('shop/cart/cart.html.twig', [
            'cart' => $cart,
//            'featuredProduct' => $featuredProduct,
//            'addToCartForm' => $addToCartForm->createView()
        ]);
    }

	#[Route(path : '/product/{slug}', name: 'app_product_show', methods: ['GET', 'POST'])]
    public function addItemToCart(
		Product $product,
		Request $request,
		CategoryRepository $categoryRepository,
		CartStorage $cartStorage
	): RedirectResponse | Response
	{
        $addToCartForm = $this->createForm(AddItemToCartFormType::class, null, [
            'product' => $product
        ]);

        $addToCartForm->handleRequest($request);
        if ($addToCartForm->isSubmitted() && $addToCartForm->isValid()) {
            $cart = $cartStorage->getOrCreateCart();
            $cart->addItem($addToCartForm->getData());
            $cartStorage->save($cart);

            $this->addFlash('success', t('item_added'));

            return $this->redirectToRoute('app_product_show', [
                'slug' => $product->getSlug(),
            ]);
        }

        return $this->renderForm('shop/product/show.html.twig', [
            'product' => $product,
            'categories' => $categoryRepository->findAll(),
            'addToCartForm' => $addToCartForm,
	        'cart' => $cartStorage->getOrCreateCart(),
        ]);
    }

	#[Route(path : '/panier/update/{productId}/{colorId?}', name : 'app_cart_update_item', methods : ['POST'])]
	public function updateItemToCart(
		$productId,
		$colorId,
		Request $request,
		CartStorage $cartStorage,
		ProductRepository $productRepository,
		ColorRepository $colorRepository
	): Response
	{
		/** @var Product|null $product */
		$product = $productRepository->find($productId);
		/** @var Color|null $color */
		$color = $colorId ? $colorRepository->find($colorId) : null;

		if (!$product) {
			throw $this->createNotFoundException();
		}

		if (!$this->isCsrfTokenValid('update_item', $request->request->get('_token'))) {
			throw new BadRequestHttpException('Invalid CSRF token');
		}

		$cart = $cartStorage->getOrCreateCart();
		$cartItem = $cart->findItem($product, $color);
		if ($cartItem) {
			$cartItem->setQuantity($request->request->getInt('quantity'));
		}
		$cartStorage->save($cart);

		$this->addFlash('success', 'Item removed!');

		if($request->isXmlHttpRequest()) {
			return $this->render('shop/cart/_item.html.twig', [
				'item' => $cartItem,
			]);
		}

		return $this->redirectToRoute('app_cart');
	}

	#[Route(
		path: '/panier/summary',
		name: 'app_cart_summary',
		methods: ['GET'],
		condition: 'request.isXmlHttpRequest()'
	)]
	public function cartSummary(CartStorage $cartStorage): Response
	{
		return $this->render('shop/cart/cart_summary.html.twig', [
			'cart' => $cartStorage->getOrCreateCart(),
		]);
	}

	#[Route(path : '/panier/remove/{productId}/{colorId?}', name : 'app_cart_remove_item', methods : ['POST'])]
    public function removeItemToCart($productId, $colorId, Request $request, CartStorage $cartStorage, ProductRepository $productRepository, ColorRepository $colorRepository): RedirectResponse
	{
        /** @var Product|null $product */
        $product = $productRepository->find($productId);
        /** @var Color|null $color */
        $color = $colorId ? $colorRepository->find($colorId) : null;

        if (!$product) {
            $this->createNotFoundException();
        }

        if (!$this->isCsrfTokenValid('remove_item', $request->request->get('_token'))) {
            throw new BadRequestHttpException('Invalid CSRF token');
        }

        $cart = $cartStorage->getOrCreateCart();
        $cartItem = $cart->findItem($product, $color);
        if ($cartItem) {
            $cart->removeItem($cartItem);
        }
        $cartStorage->save($cart);

        $this->addFlash('success', 'Item removed!');

        return $this->redirectToRoute('app_cart');
    }

	#[Route(path: '/panier/_list', name : '_app_cart_list')]
	public function _shoppingCartList(CartStorage $cartStorage): Response
	{
		return $this->render('shop/cart/_cartList.html.twig', [
			'cart' => $cartStorage->getOrCreateCart()
		]);
	}
}

src/Client/Controller/Shop/CheckoutController.php
<?php

namespace App\Client\Controller\Shop;


use App\Application\Purchase\Purchase;
use Doctrine\ORM\EntityManagerInterface;
use App\Infrastructure\Service\CartStorage;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Application\Product\ProductRepository;
use Symfony\Component\Routing\Annotation\Route;
use App\Application\Purchase\PurchaseRepository;
use App\Application\Purchase\Form\CheckoutFormType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CheckoutController extends AbstractController
{
	public function __construct(private readonly EntityManagerInterface $entityManager) { }

	#[Route(path: "/checkout", name: "app_checkout")]
    public function checkout(
		ProductRepository $productRepository,
		Request $request,
		CartStorage $cartStorage,
		EntityManagerInterface $entityManager,
		SessionInterface $session
	): Response
	{
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

		$cart = $cartStorage->getCart();
		if(!$cart){
			$this->addFlash("warning", "cart.empty");
			return $this->redirectToRoute('app_cart');
		}

        $checkoutForm = $this->createForm(CheckoutFormType::class);
        $featuredProduct = $productRepository->findFeatured();
        /*$addToCartForm = $this->createForm(AddItemToCartFormType::class, null, [
            'product' => $featuredProduct,
        ]);*/

        $checkoutForm->handleRequest($request);
        if ($checkoutForm->isSubmitted() && $checkoutForm->isValid()) {
            /** @var Purchase $purchase */
            $purchase = $checkoutForm->getData();
			$purchase
				->setCustomer($this->getUser())
				->setOrderNumber($this->generateOrderNumber())
				->setConfirmed(false)
			;
            $purchase->addItemsFromCart($cartStorage->getCart());

            $entityManager->persist($purchase);
            $entityManager->flush();

            $session->set('purchase_id', $purchase->getId());
            $cartStorage->clearCart();

            return $this->redirectToRoute('app_confirmation');
        }

        return $this->render('shop/checkout/checkout.html.twig', [
            'checkoutForm' => $checkoutForm->createView(),
            'featuredProduct' => $featuredProduct,
	        'cart' => $cart,
        ]);
    }

	private function generateOrderNumber()
	{
		return $this->entityManager->getRepository(Purchase::class)->getLatestOrderNumber() + 1;
	}

    /**
     * @Route("/confirmation", name="app_confirmation")
     */
    public function confirmation(SessionInterface $session, PurchaseRepository $purchaseRepository): Response
    {
        $purchaseId = $session->get('purchase_id');
		if(!$purchaseId) {
			$this->addFlash('warning', 'cart.empty');
			return $this->redirectToRoute('app_cart');
		}
        $purchase = $purchaseRepository->find($purchaseId);

        if (!$purchase) {
            throw $this->createNotFoundException('No purchase found');
        }

        return $this->render('checkout/confirmation.html.twig', [
            'purchase' => $purchase,
        ]);
    }
}

src/Client/Controller/Shop/ProductController.php
<?php

namespace App\Client\Controller\Shop;

use App\Application\Shop\Data\SearchData;
use App\Application\Shop\Form\SearchForm;
use App\Client\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Application\Product\ProductRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

class ProductController extends AbstractController
{
	#[Route('/boutique', name: 'product_index')]
	public function shop(ProductRepository $repo, Request $request): Response
	{
		$data = new SearchData();
		$data->page = $request->get('page', 1);

		$searchForm = $this->createForm(SearchForm::class, $data);
		$searchForm->handleRequest($request);

		[$min, $max] = $repo->findMinMax($data);

		$products = $repo->findSearch($data);

		if ($request->get('ajax')) {
			return new JsonResponse([
				'content' => $this->renderView('shop/product/_products.html.twig', ['products' => $products]),
				'pagination' => $this->renderView('shop/product/_pagination.html.twig', ['products' => $products]),
				'sorting' => $this->renderView('shop/product/_sorting.html.twig', ['products' => $products]),
			]);
		}

		return $this->renderForm('shop/product/index.html.twig', [
			'products' => $products,
			'searchForm' => $searchForm,
			'min' => $min,
			'max' => $max,
		]);
	}
}

templates/shop/cart/_cartList.html.twig
<div class="container custom-area mb-4">
	<div class="row">
		<div class="col-lg-12 col-custom">
			<div class="cart-table table-responsive">
				{% if cart.items|length > 0 %}
					<table class="table table-bordered">
						<thead>
							<tr>
								<th class="pro-thumbnail">Image</th>
								<th class="pro-title">Product</th>
								<th class="pro-price">Price</th>
								<th class="pro-quantity">Quantity</th>
								<th class="pro-subtotal">Total</th>
								<th class="pro-remove">Remove</th>
							</tr>
						</thead>
						<tbody>
							{% for item in cart.items %}
									{% set product = item.product %}
									<tr>
										<td class="pro-thumbnail">
											<a href="{{ path('app_product_show', {slug : item.product.slug}) }}">
												{% if product.thumbnail %}
													<picture>
														<source srcset="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_webp') }}" type="image/webp">
														<source srcset="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_jpeg') }}" type="image/jpeg">
														<img
															width="138"
															height="138"
															loading="lazy"
															src="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_jpeg') }}"
															alt="{{ product.name ~ '_image' }}"
															class="img-fluid"
														>
													</picture>
												{% else %}
													<img
														height="138"
														width="138"
														src="{{ product.thumbnailUrl }}"
														alt="{{ product.name ~ '_image' }}"
														class="img-fluid"
													>
												{% endif %}
											</a>
										</td>
										{#<div class="col-1">
											{% if item.color %}
												<span class="color-square" style="background-color: rgb({{ item.color.red }}, {{ item.color.green }}, {{ item.color.blue }});"></span>
											{% endif %}
										</div>#}
										<td class="pro-title"><a href="#">{{ product.name }}</a></td>
										<td class="pro-price"><span>{{ item.product.fixedPrice | format_currency('XOF', locale='fr') }}</span></td>
										<td class="pro-quantity">
											<form
												class="quantity"
												style="display: inline-block;"
												action="{{ path('app_cart_update_item', {
													productId: item.product.id,
													colorId: item.color ? item.color.id: null
												}) }}"
												method="POST"
											>
												<input type="hidden" name="_token" value="{{ csrf_token('update_item') }}">
												<div class="cart-plus-minus" {{ stimulus_controller('input-count-box') }}>
													<input class="cart-plus-minus-box" value="{{ item.quantity }}" type="text" {{ stimulus_target('input-count-box', 'input') }}>
													<div class="dec qtybutton" {{ stimulus_action('input-count-box', 'decrement', 'click') }}><i class="fa fa-minus"></i></div>
													<div class="inc qtybutton" {{ stimulus_action('input-count-box', 'increment', 'click') }}><i class="fa fa-plus"></i></div>
												</div>
												<button type="submit" hidden="hidden">Update</button>
											</form>
										</td>
										<td class="pro-subtotal"><span>{{ item.total | format_currency('XOF', locale='fr') }}</span></td>
										<td class="pro-remove">
											<form
												style="display: inline-block;"
												action="{{ path('app_cart_remove_item', {
													productId: item.product.id,
													colorId: item.color ? item.color.id : null,
												}) }}"
												method="POST"
											>
												<input type="hidden" name="_token" value="{{ csrf_token('remove_item') }}" />
												<button type="submit"><i class="fa fa-trash"></i></button>
											</form>
										</td>
									</tr>
								{% endfor %}
						</tbody>
					</table>
				{% else %}
					<div>
						{{ 'cart_empty'|trans }}
						<button class="btn flosun-button primary-btn rounded-0 black-btn">{{ 'get_to_shopping'|trans }}</button>
					</div>
				{% endif %}
			</div>

			{% if cart.items|length > 0 %}
				{{ include('shop/cart/_coupon.html.twig') }}
			{% endif %}

		</div>
	</div>

	{% if cart.items|length > 0 %}
		<div class="row">
			<div class="col-lg-5 ml-auto col-custom">
				{{ include('shop/cart/_cart_total.html.twig', { cart : cart })}}
			</div>
		</div>
	{% endif %}
</div>

templates/shop/cart/_cart_total.html.twig
<div class="cart-calculator-wrapper">
	<div class="cart-calculate-items">
		<h3>{{ 'cart_totals'|trans }}</h3>
		<div class="table-responsive">
			<table class="table">
				<tr>
					<td>{{ 'sub_total'|trans }}</td>
					<td>{{ cart.total | format_currency('XOF', locale='fr') }}</td>
				</tr>
				<tr>
					<td>Shipping</td>
					<td>$70</td>
				</tr>
				<tr class="total">
					<td>{{ 'total'|trans }}</td>
					<td class="total-amount">{{ cart.total | format_currency('XOF', locale='fr') }}</td>
				</tr>
			</table>
		</div>
	</div>
	<a href="{{ path('app_checkout') }}" class="btn flosun-button primary-btn rounded-0 black-btn w-100">{{ 'proceed_to_checkout'|trans }}</a>
</div>

templates/shop/cart/_coupon.html.twig
<div class="cart-update-option d-block d-md-flex justify-content-between">
	<div class="apply-coupon-wrapper">
		<form action="#" method="post" class=" d-block d-md-flex">
			<input type="text" placeholder="Enter Your Coupon Code" required />
			<button class="btn flosun-button primary-btn rounded-0 black-btn">Apply Coupon</button>
		</form>
	</div>
	<div class="cart-update mt-sm-16">
		<a href="#" class="btn flosun-button primary-btn rounded-0 black-btn">Update Cart</a>
	</div>
</div>

templates/shop/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="breadcrumbs-area position-relative">
		<div class="container">
			<div class="row">
				<div class="col-12 text-center">
					<div class="breadcrumb-content position-relative section-content">
						<h3 class="title-3">Shopping Cart</h3>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>Shopping Cart</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div
		class="cart-main-wrapper mt-no-text"
		{{ stimulus_controller('reload-content', {
			url: path('_app_cart_list'),
		}) }}
	>
		{{ include('shop/cart/_cartList.html.twig')}}
	</div>
{% endblock %}

{% block meta %}
	<meta name="robots" content="noindex, nofollow">
{% endblock %}

templates/shop/cart/cart_summary.html.twig
<div class="minicart__header ">
	<div class="minicart__header--top d-flex justify-content-between align-items-center">
		<h3 class="minicart__title"> Shopping Cart</h3>
		<button class="minicart__close--btn" aria-label="minicart close btn" data-offcanvas>
			<svg class="minicart__close--icon" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 512 512"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M368 368L144 144M368 144L144 368"/></svg>
		</button>
	</div>
</div>
{% if not cart.empty %}
	<div class="minicart__product">
		{% for key, item in cart.items %}
			{% set product = item.product %}
			<div class="minicart__product--items d-flex">
				<div class="minicart__thumb">
					<a href="{{ path('app_cart'}) }}">
						{% if product.thumbnail %}
							<picture>
								<source srcset="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_webp') }}" type="image/webp">
								<source srcset="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_jpeg') }}" type="image/jpeg">
								<img
									width="78"
									height="78"
									loading="lazy"
									src="{{ (thumbnailPath ~ product.thumbnailUrl) | imagine_filter('small_product_thumb_jpeg') }}"
									alt="{{ product.name ~ '_image' }}"
									class="product-img">
							</picture>
						{% else %}
							<img
								width="78"
								height="78"
								class="product-img"
								loading="lazy"
								src="{{ product.thumbnailUrl }}"
								alt="{{ product.name ~ '_image' }}"
							>
						{% endif %}
					</a>
				</div>
				<div class="minicart__text">
					<h4 class="minicart__subtitle">
						<a href="{{ path('app_cart') }}">{{ product.name }}</a>
					</h4>
					<span class="color__variant"><b>Color:</b> {{ item.color ?? "" }}</span>
					<div class="minicart__price">
						<span class="minicart__current--price">{{ item.product.fixedPrice | format_currency('XOF', locale='fr') }}</span>
						<span class="minicart__old--price">{{ item.product.fixedPrice | format_currency('XOF', locale='fr') }}</span>
					</div>
					<div class="minicart__text--footer d-flex align-items-center">
						<div class="quantity__box minicart__quantity">
							<button type="button" class="quantity__value decrease" aria-label="quantity value" value="Decrease Value">-</button>
							<label>
								<input type="number" class="quantity__number" value="1" data-counter />
							</label>
							<button type="button" class="quantity__value increase" aria-label="quantity value" value="Increase Value">+</button>
						</div>
						<form
								style="display: inline-block;"
								action="{{ path('app_cart_remove_item', {
									productId: item.product.id,
									colorId: item.color ? item.color.id : null,
								}) }}"
								method="POST"
						>
							<input type="hidden" name="_token" value="{{ csrf_token('remove_item') }}" />
							<button class="minicart__product--remove" type="submit">{{ 'remove'|trans }}</button>
						</form>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<div class="minicart__amount">
		<div class="minicart__amount_list d-flex justify-content-between">
			<span>Sub Total:</span>
			<span><b>{{ cart.total | format_currency('XOF', locale='fr') }}</b></span>
		</div>
		<div class="minicart__amount_list d-flex justify-content-between">
			<span>Total:</span>
			<span><b>{{ cart.total | format_currency('XOF', locale='fr') }}</b></span>
		</div>
	</div>
	<div class="minicart__button d-flex justify-content-center">
		<a class="primary__btn minicart__button--link" href="{{ path('app_cart') }}">View cart</a>
		<a class="primary__btn minicart__button--link" href="{{ path('app_checkout') }}">Checkout</a>
	</div>
{% else %}
	<div class="minicart__conditions text-center">
		Votre panier est vide
		<a class="minicart__conditions--link" href="">Découvrir nos produits</a>
	</div>
{% endif %}